const express = require('express')
const morgan = require('morgan')
const authRouter = require('./routers/authRouter')
const userRouter = require('./routers/userRouter')
const {connectMysql} = require('./databases/connect')
const cors = require('cors')

const relationship = require('./models/relationship')
const errorMiddleware = require('./middlewares/errorMiddleware')
const categoryRouter = require('./routers/CategoryRouter')
const brandRouter = require('./routers/BrandRouter')
const productRouter = require('./routers/productRouter')
const app = express()
const port = 4000
app.use(express.json())
app.use(morgan('dev'))
app.use(express.urlencoded({ extended: true }))
app.use(cors())

connectMysql()
app.use('/api/v1/auth',authRouter)
app.use('/api/v1/user',userRouter)
app.use('/api/v1/categories',categoryRouter)
app.use('/api/v1/brands',brandRouter)
app.use('/api/v1/products',productRouter)
app.use (errorMiddleware)
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})